# Generated by Django 5.2.10 on 2026-10-05 22:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('area', models.CharField(choices=[('Ficção', 'Ficção'), ('Fantasia', 'Fantasia'), ('Romance', 'Romance'), ('Suspense', 'Suspense / Mistério'), ('Ficção Científica', 'Ficção Científica'), ('Tecnologia', 'Tecnologia'), ('Ciência', 'Ciência'), ('História', 'História'), ('Filosofia', 'Filosofia'), ('Autoajuda', 'Autoajuda'), ('Negócios', 'Negócios'), ('Educação', 'Educação'), ('Arte', 'Arte'), ('Poesia', 'Poesia'), ('Infantil', 'Infantil')], default='Ficção', max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=30)),
                ('capa_url', models.URLField(blank=True, help_text='Link da capa (opcional, ideal p/ feira)')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('estoque_total', models.PositiveIntegerField(default=3)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_prevista', models.DateTimeField()),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('devolvido', 'Devolvido'), ('atrasado', 'Atrasado')], default='ativo', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='core.livro')),
            ],
            options={
                'ordering': ['-data_emprestimo'],
            },
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('area', models.CharField(choices=[('Ficção', 'Ficção'), ('Fantasia', 'Fantasia'), ('Romance', 'Romance'), ('Suspense', 'Suspense / Mistério'), ('Ficção Científica', 'Ficção Científica'), ('Tecnologia', 'Tecnologia'), ('Ciência', 'Ciência'), ('História', 'História'), ('Filosofia', 'Filosofia'), ('Autoajuda', 'Autoajuda'), ('Negócios', 'Negócios'), ('Educação', 'Educação'), ('Arte', 'Arte'), ('Poesia', 'Poesia'), ('Infantil', 'Infantil')], default='Ficção', max_length=50)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('destaque', models.BooleanField(default=False)),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('livros', models.ManyToManyField(blank=True, related_name='colecoes', to='core.livro')),
            ],
            options={
                'ordering': ['-destaque', '-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('match', 'Match literário'), ('emprestimo', 'Empréstimo'), ('sistema', 'Sistema')], default='sistema', max_length=20)),
                ('mensagem', models.CharField(max_length=280)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='core.livro')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('usuario', 'livro')},
            },
        ),
        migrations.CreateModel(
            name='MatchLiterario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.livro')),
                ('usuario1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_1', to=settings.AUTH_USER_MODEL)),
                ('usuario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('livro', 'usuario1', 'usuario2'), name='match_unico')],
            },
        ),
    ]
