# Generated by Django 5.2.10 on 2026-10-05 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='prazo_dias',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='renovacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('match', 'Match literário'), ('emprestimo', 'Empréstimo'), ('reserva', 'Reserva'), ('sistema', 'Sistema')], default='sistema', max_length=20),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
                ('atendida_em', models.DateTimeField(blank=True, null=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criada_em'],
            },
        ),
    ]
