# Generated by Django 5.2.17 on 2026-10-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emprestimo_prazo_dias_emprestimo_renovacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telefone_publico',
            field=models.BooleanField(default=True, help_text='Se marcado, outros leitores com match poderão ver seu número.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(help_text='Somente números com DDD. Ex: 11999998888', max_length=20),
        ),
    ]
